import { Poppins } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Head from "next/head";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // Specify the weights you need
});

export const metadata = {
    title: {
        default: "Cluster Coffee",
        template: "%s | Cluster Coffee",
    },
    description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
    const { locale } = await params;
    console.log(locale);
    const messages = await getMessages({ locale: locale });

    return (
        <html lang={locale}>
            <Head>
                <link
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
                    rel="stylesheet"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Poppins:wght@300;400;500;600&display=swap"
                    rel="stylesheet"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Poppins:wght@300;400;500;600&display=swap"
                    rel="stylesheet"
                />
                <script src="https://cdn.tailwindcss.com/3.4.5?plugins=forms@0.5.7,typography@0.5.13,aspect-ratio@0.4.2,container-queries@0.1.1" />
                <script
                    src="https://ai-public.creatie.ai/gen_page/tailwind-config.min.js"
                    data-color="#000000"
                    data-border-radius="medium"
                />
            </Head>
            <body
                className={`${poppins.variable} antialiased bg-gray-50 font-[Poppins] font-black h-screen`}
            >
                <NextIntlClientProvider messages={messages}>
                    <Navbar />
                    {children}
                    <Footer />
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
